bot: {automerge: true}
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
test: native_and_emulated